#!/usr/bin/env node

const fs = require( 'fs' );
const path = require( 'path' );

const basePath = __dirname.replace( /(\\|\/)scripts$/, '' )

addDefaultFiles( 'blacklist.txt', '' )
addDefaultFiles( 'channels.db', '{}' )
addDefaultFiles( 'translations.db', '{}' )
addDefaultFiles( '.env',
	[
		'PORT=8000',
		'TWITCHUSER=[FidFixc]',
		'OAUTH=[oauth:0ac1h2rx17s8xryh274hi4zc66vn1h] # e.g. OAUTH=oauth:kjh12bn1hsj78445234',
		'YANDEX_KEY=[b1guii94bpc12f91fmc8] # e.g. from https://translate.yandex.com/developers/keys',
	].join( '\n' ) + '\n'
)

function addDefaultFiles( name, defaultContent ) {
	const filePath = path.join( basePath, name )
	if( !fs.existsSync( filePath ) ) {
		fs.writeFileSync( filePath, defaultContent )
	}
}
